#!/bin/bash
#SBATCH -J rfdiffusion
#SBATCH -o rossSCS_%j.out
#SBATCH -e rossSCS_%j.err
#SBATCH -p gpu-a100
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -t 01:00:00
#SBATCH -A CHE23010

module load gcc/12.2.0
module load cuda
eval "$(command conda 'shell.bash' 'hook' 2> /dev/null)"
conda activate ca_rfd_release
export PYTHONPATH=$PYTHONPATH:/work/10391/kaileeshlipak/ls6/CA_RFDiffusion

cd /work/10391/kaileeshlipak/ls6/CA_RFDiffusion

python run_inference.py \
  --config-path ./rf_diffusion/config/inference \
  --config-name lisa_working_copy \
  inference.output_prefix=designs_nifD0830/ross+16AngSCS \
  inference.num_designs=10
